config/routes.rb
SlumlordWordPress::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  root to: 'static_pages#home'

  match '/ip/', to: 'users#ip'
  match '/me', to: 'users#show'
  match '/about', to: 'static_pages#about'
  match '/signup', to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password, :password_confirmation, :secure_ip
  has_secure_password

  before_save { |user| user.email = email.downcase }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,
     format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper

  # Force signout to prevent CSRF attacks
  def handle_unverified_request
    sign_out
    super
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_email(params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_back_or user
    else
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
  end

  def about
  end

end

app/controllers/users_controller.rb
require 'rubygems'
require 'json'
require 'digest/md5'

class UsersController < ApplicationController
  before_filter :signed_in_user, only: [:show, :ip]

  def ip
    @user = User.find(session[:user_id])
    if params[:ip].blank?
      if !@user.secure_ip.nil?
        iptables_remove_ip @user.secure_ip
        @user.secure_ip = nil;
        @user.save!(validate: false)
        flash[:success] = "Your WordPress server is now accessible by anyone."
      end
    else
      if !check_ip(params[:ip])
        flash[:error] = "Wrong IP format"
      else
        if !@user.secure_ip.nil?
          iptables_remove_ip(@user.secure_ip)
        end
        iptables_add_ip(params[:ip])
        @user.secure_ip = params[:ip]
        @user.save(validate: false)
        flash[:success] = "Your WordPress server will now work only with requests from IP #{@user.secure_ip}."
      end
    end
    redirect_to me_path
  end

  def index
    redirect_to root_path
  end

  def new
    @user = User.new
  end

  def show
    @user = current_user
    @md5 = digest = Digest::MD5.hexdigest(@user.email)[0...11]
  end

  def create
    @user = User.new(params[:user])
    @user.secure_ip = nil;
    create_wordpress_instance
    if @user.save
      sign_in @user
      flash[:success] = "Welcome!"
      redirect_to me_path
    else
      render 'new'
    end
  end
  
  private

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_url, notice: "Please sign in."
    end
  end

  def create_wordpress_instance
    docker_path = '/usr/bin/'
    container_id = `#{docker_path}docker run -d slumlord/wordpress`
    cmd = "#{docker_path}docker inspect #{container_id}"
    json_infos = `#{cmd}`
    i = JSON.parse(json_infos)
    @user.memcached = i[0]["NetworkSettings"]["PortMapping"]["Tcp"]["80"]
    @user.container_id = container_id
    @user.docker_ip = i[0]["NetworkSettings"]["IpAddress"]
  end
  
  $VALIDATE_IP_REGEX = /^([01]?\d\d?|2[0-4]\d|25[0-5])\.([01]?\d\d?|2[0-4]\d|25[0-5])\.([01]?\d\d?|2[0-4]\d|25[0-5])\.([01]?\d\d?|2[0-4]\d|25[0-5])$/  
  def check_ip(i)
    if ($VALIDATE_IP_REGEX.match(i))
      return true;
    end
    return false;
  end
  
  def iptables_add_ip(i)
    cwd = Dir.pwd
    `sudo #{cwd}/iptables/add_ip #{@user.docker_ip} #{i}`
  end

  def iptables_remove_ip(i)
    cwd = Dir.pwd
    `sudo #{cwd}/iptables/remove_ip #{@user.docker_ip} #{i}`
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Slumlord WordPress"
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end

end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    session[:user_id] = user.id
    current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def sign_out
    current_user = nil
    session.delete(:user_id);
  end
  
  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= session[:user_id] and User.find(session[:user_id])
  end

  def current_user?(user)
    user == current_user
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url
  end

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_url, notice: "Plese sign in."
    end
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
require 'net/http'
require 'rubygems'
require 'json'

module UsersHelper

  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.email, class: "gravatar")
  end

  def my_public_ip
    @@ip ||= Net::HTTP.get_response(URI.parse("http://ipv4.icanhazip.com")).body.chomp
  end

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Find the source on <a href="https://github.com/hhoover/slumlord-wordpress">GitHub</a>
  </small>
  <nav>
    <ul>
      <li>
	<a href="http://www.slideshare.net/julienbarbier42/building-a-saas-using-docker">Build your own SaaS using docker</a>
      </li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Slumlord WordPress", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "About", about_path %></li>
          <% if signed_in? %>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", me_path %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, 'About this project') %>
<h1>Slumlord WordPress with Docker</h1>
<p>This should not be used by anyone.</p>
<p>
  Original project: <a href="https://github.com/jbarbier/SaaS_Memcached">SaaS_Memcached</a>
</p>
<p>
  Get the code for what you are seeing here: <a href="https://github.com/hhoover/slumlord-wordpress">Slumlord WordPress</a>
</p>

app/views/static_pages/home.html.erb
<% provide(:title, 'Slumlord WordPress') %>
<div class="center hero-unit">
  <h1>Get your WordPress here!</h1>

  <h2>Sign up to get your own WordPress instance!</h2>

  <%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>
</div>

app/views/users/_ip.html.erb
<div class="alert alert-info">
  In order to secure your WordPress server you can restrict its access by IP. If you do so, only clients from this IP will be able to access it.
</div>
<h1>
  Secure your WordPress server
</h1>
<div class="row">
  <div class="span3 offset3">
    <%= form_tag("/ip", :method => "get") do %>
    <%= label_tag(:ip, "Enter your IP") %>
    <%= text_field_tag(:ip, @user.secure_ip)  %>
    <%= submit_tag("Save", class:"btn btn-large btn-primary") %>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>
      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.email) %>
<h1>
  <%= gravatar_for @user %>
  <%= @user.email %>
</h1>
<div class="alert alert-info">
  Congratulations <%= @user.email %>. Your WordPress server is ready to use.
</div>
<h1>Your WordPress Server is ready!</h1>
<div class="block-info">
  <h3>IP: <%= my_public_ip %></h3>
  <h3>PORT: <%= @user.memcached %></h3>
</div>
<div class="alert alert-info">
  Happy Blogging
</div>